name: Validação HTML

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Validação do HTML
        uses: Cyb3r-Jak3/html5validator-action@v0.4.4
        with:
          root: .
          log_level: WARNING
